### ISSUE TITLE
Include message template in case of format error

### ISSUE THREAD

**Issue by slorber** [yahoo/react-intl#116]
Hi,

In my large translated app, I sometimes have errors like `Error: A value must be provided for: categoryName`
Messages can get even more obscure when using more complex formatting.

The problem is that sometimes it can be quite difficult to find out which message template has a problem (like in this case a missing argument).

Unfurtunately it seems the stack does not help me find out which component lead to this exception thrown during the format:

```
Error: A value must be provided for: categoryName
    at MessageFormat._format (http://localhost:8080/app.js:3701:19)
    at MessageFormat.format (http://localhost:8080/app.js:3551:30)
    at exports.default.formatMessage (http://localhost:8080/app.js:3070:24)
    at src$react$$.default.createClass.render (http://localhost:8080/app.js:2790:37)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (http://localhost:8080/appLibs.js:47859:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (http://localhost:8080/appLibs.js:47885:14)
    at ReactDefaultPerf.measure (http://localhost:8080/appLibs.js:50495:19)
    at ReactPerf.measure.wrapper (http://localhost:8080/appLibs.js:54422:31)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:8080/appLibs.js:47319:30)
    at ReactDefaultPerf.measure (http://localhost:8080/appLibs.js:50495:19) 
```

Can it be possible to include the message template in the format error? it would help to make debugging easier

**Comment by ericf** [comment]
> Can it be possible to include the message template in the format error?

Yes, this is a good idea. This change should be made in: https://github.com/yahoo/intl-messageformat

Also, the plan is to have a better fallback story in a future version of this lib so that developers can decide how they want to handle the fallback.

**Comment by ericf** [comment]
See: #162
