### ISSUE TITLE
is v2.0.0-pr-1 working with react 0.13.x?

### ISSUE THREAD

**Issue by eriknyk** [yahoo/react-intl#172]
Hi, I'm trying to implement react-intl v2.0.0-pr-1 with react v0.13.x
and I have the following error.

```
Warning: Failed Context Types: Required context `intl` was not specified in `FormattedNumber`. Check the render method of `Blank`.
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `[object Object]`) for key (intl) while mounting FormattedNumber (see: http://fb.me/react-context-by-parent)
/Users/erik/towbook/towbook-foundation/node_modules/react-intl/lib/components/number.js:41
        var formatNumber = this.context.intl.formatNumber;
                                            ^

TypeError: Cannot read property 'formatNumber' of undefined
    at FormattedNumber.render (/Users/erik/towbook/towbook-foundation/node_modules/react-intl/lib/components/number.js:41:45)
    at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/erik/towbook/towbook-foundation/node_modules/react/lib/ReactCompositeComponent.js:789:34)

```

any suggestion?

Best Regards.

**Comment by kyleboyle** [comment]
There are context issues. Are you rendering like this to force owner context:
```<IntlProvider locale=... messages=...>
      {() => (
        <MyApp/>
      )}
</IntlProvider>```

I am getting a similar issue when using react-router. When rendering components with children that are defined in my routes, anything that gets rendered below the first {this.props.children} doesn't have access to the correct context. I'm not sure how to fix that one.

**Comment by kyleboyle** [comment]
Just answering my own problem, upgrading to react 0.14 fixes the context issue for me with mixing react-router and react-intl

**Comment by ericf** [comment]
@kyleboyle I'm planning to make v2 only work with React 0.14.0 and onward. I've been finding too many issues like you described when trying to support 0.13 as well.
