### ISSUE TITLE
Get socket error when using https

### ISSUE THREAD

**Issue by zkirill** [yahoo/react-intl#198]
Getting this error for https://localhost:5000/ when using self-signed certificates.

```bash
Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at Socket.socketOnEnd (_http_client.js:288:23)
    at emitNone (events.js:72:20)
    at Socket.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

Interestingly this URL resolves correctly: https://localhost:5000/api/content?path=about

Modifications to server.js to support https
```javascript
var options = {
  key: fs.readFileSync('server.key'),
  cert: fs.readFileSync('server.crt'),
  ca: fs.readFileSync('ca.crt'),
  requestCert: false,
  rejectUnauthorized: false
};

https.createServer(options, server).listen(port);
```

Not sure but maybe this is related http://stackoverflow.com/a/23637556.

**Comment by zkirill** [comment]
Apologies, wrong repo.
