### ISSUE TITLE
node 5.3 RangeError: timeZone is not supported. 

### ISSUE THREAD

**Issue by rkoberg** [yahoo/react-intl#276]
"react-intl": "^2.0.0-pr-1",
This was working on the client, but not on the server:
```
<FormattedDate
  day="numeric"
  month="short"
  timeZone="America/Chicago"
  value={date}
  year="numeric"
/>
```
```
RangeError: timeZone is not supported.
   at InitializeDateTimeFormat (/Users/rkoberg/Sites/tp/node_modules/intl/lib/core.js:1854:19)
   at new DateTimeFormatConstructor (/Users/rkoberg/Sites/tp/node_modules/intl/lib/core.js:1739:12)
   at Object.getDateTimeFormat (/Users/rkoberg/Sites/tp/node_modules/intl-format-cache/lib/memoizer.js:17:31)
   at formatDate (/Users/rkoberg/Sites/tp/node_modules/react-intl/lib/format.js:63:17)
   at FormattedDate.render (/Users/rkoberg/Sites/tp/node_modules/react-intl/lib/components/date.js:50:29)
   at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext 
```

**Comment by ericf** [comment]
This is a Node.js issue, you should report it there. See: https://github.com/nodejs/node#intl-ecma-402-support

**Comment by rkoberg** [comment]
Well that's a buzz wrecker. Do you know of a way to easily run multiple versions of node taking this into account? something like ```nvm install 5.3 --intl```, pretty please?

**Comment by efkan** [comment]
This issue is being occurred when react-native running in debug mode.

        if (process.env.NODE_ENV !== 'production') {
            console.error('[React Intl] Error formatting date.\n' + e);
        }

However, if it is not in debug mode `Intl.formatDate()` returns the correct text. 

I just wonder that is there any harm setting `timeZone` argument when using `Intl.formatDate()` method in production?

@ericf , could this issue be fixed?
