### ISSUE TITLE
React Intl puts things on components' state and Jest tests fail

### ISSUE THREAD

**Issue by alejandroiglesias** [yahoo/react-intl#315]
Hi, I was trying to run/fix all my (Jest) unit tests. Got them to run (see #308) but now they fail because i cannot check for components' state since it seems to be altered by React Intl.
Here's an example:

```
 FAIL  public/scripts/comment/__tests__/CommentForm-test.js (1.537s)
● CommentForm component › it sets a default initial state
  - Expected: {
    | getDateTimeFormat: undefined,
    | getMessageFormat: undefined,
    | getNumberFormat: undefined,
    | getPluralFormat: undefined,
    | getRelativeFormat: undefined,
    | now: Function
    } toEqual: {
    | author: '',
    | text: ''
    }
```

Since i'm new to React (coming from Angular) i'm wondering if it really is a good practice to put things on component state (in other words, "pollute" the state). Wouldn't make more sense to use, say, `myComponentInstance.getMessageFormat` rather than `myComponentInstance.state.getMessageFormat`? Also, why are they declared as `undefined`?

Any help is appreciated. Thanks in advance.

**Comment by ericf** [comment]
Yes, using a component's state is first-class feature of React; it's not pollution. I'm not sure why your tests involve looking into React Intl components' state.

**Comment by alejandroiglesias** [comment]
@ericf thanks for answering. As far as i know, you use components' state to save component data, pretty much like the concept of scope in Angular. Probably i should "namespace" my data to `commentForm.state.data` and check for that? Or is there any other better practice?

**Comment by ericf** [comment]
`state` is fundamental to React, I'd recommend checking the React docs for details on how it works and how to use it.

**Comment by alejandroiglesias** [comment]
@ericf thanks for the recommendation, but i already did that and built my CommentForm component based on the docs (see the [Forms section](https://facebook.github.io/react/docs/forms.html)), using state to store the values on my inputs, as the docs show. Then wrote my unit tests checking that the component was setting state properly. Everything ok until React Intl entered into the scene and put other stuff in the state. Is there anything else that i'm missing?

**Comment by ericf** [comment]
I don't understand the problem you're facing, so I don't know how to help any further. There's nothing special or unique with how React Intl uses state for its stateful components.

**Comment by alejandroiglesias** [comment]
Well, you can look at the test suite [here](https://github.com/alejandroiglesias/react-tutorial/blob/master/public/scripts/comment/__tests__/CommentForm-test.js) (you can look for example the first spec, which is the simpler):

```
jest.dontMock('../CommentForm');

import {IntlProvider} from 'react-intl';
import React from 'react';
import ReactDOM from 'react-dom';
import TestUtils from 'react-addons-test-utils';

const CommentForm = require('../CommentForm');

describe('CommentForm component', () => {
  it('sets a default initial state', () => {
    const commentForm = TestUtils.renderIntoDocument(
      <IntlProvider locale="en">
        <CommentForm />
      </IntlProvider>
    );

    expect(commentForm.state).toEqual({author: '', text: ''});
  });
  
  ...
```

And it fails like this:

```
 FAIL  public/scripts/comment/__tests__/CommentForm-test.js (1.497s)
● CommentForm component › it sets a default initial state
  - Expected: {
    | getDateTimeFormat: undefined,
    | getMessageFormat: undefined,
    | getNumberFormat: undefined,
    | getPluralFormat: undefined,
    | getRelativeFormat: undefined,
    | now: Function
    } toEqual: {
    | author: '',
    | text: ''
    }
        at Spec.eval (public/scripts/comment/__tests__/CommentForm-test.js:18:31)
```

(Line 18 is the one with the expect.)
So even though i'm setting an initial state on my `CommentForm` component of `{author: '', text: ''}` it gets overridden by 5 `undefined` functions and a `now` function. No `author` or `text` properties in there. That sounds strange to me, shouldn't the properties be there besides it's perfectly ok or not to add functions to the state?

**Comment by alejandroiglesias** [comment]
Also, do functions make the state of the component? Shouldn't be pure ("JSON-serializable", [according to the docs](https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html#what-should-go-in-state)) data? Also [in the docs](https://facebook.github.io/react/tips/expose-component-functions.html) they mention exposing component functions but they don't use state.
So i'm missing a point here?
Thanks.

**Comment by emj365** [comment]
@alejandroiglesias I'm writing jest with `react-intl` too. Almost we got same problem.

```
"use strict";

import React from 'react';
import ReactDOM from 'react-dom';

import {
  addLocaleData,
  IntlProvider,
  FormattedMessage,
  FormattedNumber,
  IntlMessageFormat
} from 'react-intl';
import TestUtils from 'react-addons-test-utils';

describe('test', () => {

  let component, renderedDOM;

  it('test', () => {
    component = TestUtils.renderIntoDocument(
      <IntlProvider locale='en'>
        <FormattedNumber
          value={1}
          maximumFractionDigits={2}
          minimumFractionDigits={2}
        />
      </IntlProvider>
    );
    console.log(component);
  });
});
```

Now I stuck with 
```
 FAIL  src/components/Quotation/__tests__/Quotation-test.js (2.13s)
● test › it test
  - TypeError: state.getNumberFormat is not a function
        at formatNumber (node_modules/react-intl/lib/format.js:115:18)
        at FormattedNumber.render (node_modules/react-intl/lib/components/number.js:62:35)
        at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (node_modules/react/lib/ReactCompositeComponent.js:587:34)
        at ReactCompositeComponentMixin._renderValidatedComponent (node_modules/react/lib/ReactCompositeComponent.js:607:32)
        at wrapper [as _renderValidatedComponent] (node_modules/react/lib/ReactPerf.js:66:21)
        at ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:220:30)
        at wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:37:35)
        at ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:225:34)
        at wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:37:35)
        at ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:225:34)
        at wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:37:35)
        at mountComponentIntoNode (node_modules/react/lib/ReactMount.js:266:32)
        at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
        at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:282:15)
        at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
        at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
        at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:94:20)
        at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:476:18)
        at Object.wrapper [as _renderNewRootComponent] (node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react/lib/ReactMount.js:550:32)
        at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:570:23)
        at Object.wrapper [as render] (node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:76:21)
        at Spec.eval (src/components/Quotation/__tests__/Quotation-test.js:20:48)
```
because:
```
state:
   { getDateTimeFormat: undefined,
     getNumberFormat: undefined,
     getMessageFormat: undefined,
     getRelativeFormat: undefined,
     getPluralFormat: undefined,
     now: [Function: now] },
```

**Comment by emj365** [comment]
@alejandroiglesias I think you made a same mistake with me. 
you tried to read state from `commentForm` which is `IntlProvider` component.
you could use `findRenderedComponentWithType` to find your `commentForm`.
I guess when you success change the state. You will get something like:
```
  - TypeError: state.getNumberFormat is not a function
```

**Comment by emj365** [comment]
I've tried to pass tests without failed with:

```javascript

    component.setState({
      getNumberFormat: function(n) {
        const fn = new (function() {
          this.format = function(n) {
            return n;
          }
        });
        return fn;
    }});
```
