### ISSUE TITLE
Failed to install examples. 

### ISSUE THREAD

**Issue by sterjakovigor** [yahoo/react-intl#569]
After "npm run build" i get

```
> react-intl@2.1.3 build:lib /Users/sterjakov/sites/react-intl
> babel-node scripts/build-lib

/Users/sterjakov/sites/react-intl/node_modules/core-js/modules/es6.promise.js:123
    if(abrupt)throw abrupt.error;
              ^

Error: Error transforming /Users/sterjakov/sites/react-intl/src/index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (/Users/sterjakov/sites/react-intl/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:43:102)
    at Object.transform$1 [as transform] (/Users/sterjakov/sites/react-intl/node_modules/rollup-plugin-babel/dist/rollup-plugin-babel.cjs.js:104:18)
    at /Users/sterjakov/sites/react-intl/node_modules/rollup/dist/rollup.js:6722:35
    at run (/Users/sterjakov/sites/react-intl/node_modules/core-js/modules/es6.promise.js:87:22)
    at /Users/sterjakov/sites/react-intl/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/Users/sterjakov/sites/react-intl/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at Function.Module.runMain (module.js:577:11)
    at /Users/sterjakov/sites/react-intl/node_modules/babel-cli/lib/_babel-node.js:160:24
```

How i can solve this problem? Thanks!

Darwin 15.6.0
node v6.3.0
npm  v3.10.5

**Comment by jiayihu** [comment]
Seems related to this issue: https://github.com/rollup/babel-preset-es2015-rollup/issues/7
I solved running this command to install the latest package from github, until the author of `babel-preset-es2015-rollup` releases a new version on npm:
`npm i git+https://github.com/rollup/babel-preset-es2015-rollup.git`

**Comment by sterjakovigor** [comment]
Ooooh thanks! It helped!

**Comment by jiayihu** [comment]
@sterjakovigor I think this issue should remain open in order to remember the contributors to update the package as soon as possible (:
Also technically it's not resolved yet and others will have the same problem meanwhile.

**Comment by ericf** [comment]
This has been resolved.
