### ISSUE TITLE
Can't build -  Error transforming react-intl\src\index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it.

### ISSUE THREAD

**Issue by tswaters** [yahoo/react-intl#724]
I'm on Windows 10, unsure if this makes a difference.

```
D:\Code>node -v
v6.6.0

D:\Code>npm -v
3.10.3

d:\Code> git clone git@github.com:yahoo/react-intl.git && cd react-intl

[snip]

d:\Code\react-intl> npm i

[snip]

> react-intl@2.1.5 prepublish D:\Code\react-intl
> npm run clean && npm run build


> react-intl@2.1.5 clean D:\Code\react-intl
> rimraf src/en.js coverage/ dist/ lib/ locale-data/


> react-intl@2.1.5 build D:\Code\react-intl
> npm run build:data && npm run build:lib && npm run build:dist


> react-intl@2.1.5 build:data D:\Code\react-intl
> babel-node scripts/build-data

Writing locale data files...

> react-intl@2.1.5 build:lib D:\Code\react-intl
> babel-node scripts/build-lib

D:\Code\react-intl\scripts\build-lib.js:56
    throw reason;
    ^

Error: Error transforming D:\Code\react-intl\src\index.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (D:\Code\react-intl\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js:43:102)
    at Object.transform$1 [as transform] (D:\Code\react-intl\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js:104:18)
    at D:\Code\react-intl\node_modules\rollup\src\utils\transform.js:19:35
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
    at Function.Module.runMain (module.js:592:11)
    at D:\Code\react-intl\node_modules\babel-cli\lib\_babel-node.js:159:24
    at Object.<anonymous> (D:\Code\react-intl\node_modules\babel-cli\lib\_babel-node.js:160:7)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:lib"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-intl@2.1.5 build:lib: `babel-node scripts/build-lib`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-intl@2.1.5 build:lib script 'babel-node scripts/build-lib'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-intl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node scripts/build-lib
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-intl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-intl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Code\react-intl\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-intl@2.1.5 build: `npm run build:data && npm run build:lib && npm run build:dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-intl@2.1.5 build script 'npm run build:data && npm run build:lib && npm run build:dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-intl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:data && npm run build:lib && npm run build:dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-intl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-intl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Code\react-intl\npm-debug.log

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! react-intl@2.1.5 prepublish: `npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-intl@2.1.5 prepublish script 'npm run clean && npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-intl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-intl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-intl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Code\react-intl\npm-debug.log
```

I updated `./scripts/build-dist` and `./scripts/build-lib` with the following:

```diff
diff --git a/scripts/build-dist.js b/scripts/build-dist.js
index 98201b0..813d5c7 100644
--- a/scripts/build-dist.js
+++ b/scripts/build-dist.js
@@ -43,7 +43,7 @@ const bundleConfig = {
 let babelConfig = JSON.parse(fs.readFileSync('src/.babelrc', 'utf8'));
 babelConfig.babelrc = false;
 babelConfig.presets = babelConfig.presets.map((preset) => {
-    return preset === 'es2015' ? 'es2015-rollup' : preset;
+    return preset === 'es2015' ? ['es2015', {modules: false }] : preset;
 });

 let plugins = [
diff --git a/scripts/build-lib.js b/scripts/build-lib.js
index 7db6722..4806ec0 100644
--- a/scripts/build-lib.js
+++ b/scripts/build-lib.js
@@ -15,7 +15,7 @@ const copyright = (
 let babelConfig = JSON.parse(fs.readFileSync('src/.babelrc', 'utf8'));
 babelConfig.babelrc = false;
 babelConfig.presets = babelConfig.presets.map((preset) => {
-    return preset === 'es2015' ? 'es2015-rollup' : preset;
+    return preset === 'es2015' ? ['es2015', {modules: false }] : preset;
 });

 let bundle = () => rollup({
```

That seems to make it build, but I'm unsure if it is functioning properly.  Tests pass!

See also: https://github.com/rollup/babel-preset-es2015-rollup/issues/11

**Comment by ericf** [comment]
Not sure why the build would run differently on unix/Mac than Windows. But feel free to create a PR for this change.

**Comment by ericf** [comment]
I think this should be fixed now. There were changes in Rollup and its plugins that were breaking the build.
