### ISSUE TITLE
Tried to contribute, failed miserably. Are there any setup instructions?

### ISSUE THREAD

**Issue by manuelbieh** [yahoo/react-intl#773]
Hi,

I cloned the repo and tried to run `npm install` which fails at the build step:

```
manuel@MANUEL-406:/mnt/d/htdocs/_git/react-intl$ npm install

> react-intl@2.1.5 prepublish /mnt/d/htdocs/_git/react-intl
> npm run clean && npm run build


> react-intl@2.1.5 clean /mnt/d/htdocs/_git/react-intl
> rimraf src/en.js coverage/ dist/ lib/ locale-data/


> react-intl@2.1.5 build /mnt/d/htdocs/_git/react-intl
> npm run build:data && npm run build:lib && npm run build:dist


> react-intl@2.1.5 build:data /mnt/d/htdocs/_git/react-intl
> babel-node scripts/build-data

Writing locale data files...

> react-intl@2.1.5 build:lib /mnt/d/htdocs/_git/react-intl
> babel-node scripts/build-lib

resolve failed:  { Error: Cannot find module 'cldr-numbers-full'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.requireRelative.resolve (/mnt/d/htdocs/_git/react-intl/node_modules/require-relative/index.js:30:17)
    at resolve (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/mnt/d/htdocs/_git/react-intl/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:541:32) code: 'MODULE_NOT_FOUND' } cldr-numbers-full
resolve failed:  { Error: Cannot find module 'cldr-dates-full'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.requireRelative.resolve (/mnt/d/htdocs/_git/react-intl/node_modules/require-relative/index.js:30:17)
    at resolve (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/mnt/d/htdocs/_git/react-intl/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:541:32) code: 'MODULE_NOT_FOUND' } cldr-dates-full
resolve failed:  { Error: Cannot find module 'cldr-core'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.requireRelative.resolve (/mnt/d/htdocs/_git/react-intl/node_modules/require-relative/index.js:30:17)
    at resolve (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/mnt/d/htdocs/_git/react-intl/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:541:32) code: 'MODULE_NOT_FOUND' } cldr-core
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.requireRelative.resolve (/mnt/d/htdocs/_git/react-intl/node_modules/require-relative/index.js:30:17)
    at resolve (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:25:26)
    at findAndRemove (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:67:11)
    at /mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:111:13
    at Array.map (native)
    at loadPreset (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/lib/serialize.js:103:29)
    at module.exports (/mnt/d/htdocs/_git/react-intl/node_modules/modify-babel-preset/index.js:97:19)
    at Object.<anonymous> (/mnt/d/htdocs/_git/react-intl/node_modules/babel-preset-es2015-rollup/index.js:3:18)
    at Module._compile (module.js:541:32) code: 'MODULE_NOT_FOUND' } babel-runtime
Treating 'intl-messageformat' as external dependency
Treating 'intl-messageformat' as external dependency
Treating 'intl-relativeformat' as external dependency
Treating 'intl-relativeformat' as external dependency
Treating 'react' as external dependency
Treating 'react' as external dependency
Treating 'invariant' as external dependency
Treating 'invariant' as external dependency
Treating 'intl-format-cache' as external dependency
Treating 'intl-format-cache' as external dependency
```

The "missing" packages (cldr-numbers-full, cldr-dates-full cldr-core, ...) are all in `node_modules/` and even after installing them explicitly the `npm run build:lib` task still failed. Tried it on Bash on Windows and Cygwin.

Do I need to install any packages globally before being able to build something? Would love to get some more information on "How to setup a working development workflow" 😉

**Comment by ericf** [comment]
Oh! It seems those packages were removed! I'll have to see what's going on and ping the Unicode folks.

**Comment by ericf** [comment]
@manuelbieh this should be fixed now. Sorry about that!
