### ISSUE TITLE
can't run translations example

### ISSUE THREAD

**Issue by jdmswong** [yahoo/react-intl#855]
```
[user@~/dir/translations]$ npm install
[user@~/dir/translations]$ npm run start

> react-intl-example-translations@1.0.0 start /Users/user/dir/translations
> cross-env ../../node_modules/.bin/babel-node src/server/index.js

sh: cross-env: command not found

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! react-intl-example-translations@1.0.0 start: `cross-env ../../node_modules/.bin/babel-node src/server/index.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the react-intl-example-translations@1.0.0 start script 'cross-env ../../node_modules/.bin/babel-node src/server/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-intl-example-translations package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env ../../node_modules/.bin/babel-node src/server/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-intl-example-translations
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-intl-example-translations
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/dir/translations/npm-debug.log
```

**Comment by jdmswong** [comment]
installing cross-env then running:
```
[user@~/dir/translations]$ sudo npm install -g cross-env
Password:
/usr/local/bin/cross-env -> /usr/local/lib/node_modules/cross-env/bin/cross-env.js
/usr/local/lib
└─┬ cross-env@3.1.4 
  └─┬ cross-spawn@3.0.1 
    ├─┬ lru-cache@4.0.2 
    │ ├── pseudomap@1.0.2 
    │ └── yallist@2.0.0 
    └─┬ which@1.2.12 
      └── isexe@1.1.2 

[user@~/dir/translations]$ npm run start

> react-intl-example-translations@1.0.0 start /Users/user/dir/translations
> cross-env ../../node_modules/.bin/babel-node src/server/index.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ../../node_modules/.bin/babel-node ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v6.9.2
npm ERR! npm  v4.0.3
npm ERR! code ELIFECYCLE
npm ERR! react-intl-example-translations@1.0.0 start: `cross-env ../../node_modules/.bin/babel-node src/server/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-intl-example-translations@1.0.0 start script 'cross-env ../../node_modules/.bin/babel-node src/server/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-intl-example-translations package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env ../../node_modules/.bin/babel-node src/server/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-intl-example-translations
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-intl-example-translations
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/dir/translations/npm-debug.log
```

**Comment by bora89** [comment]
Please, read `README`

## Running

**You first need to build the main React Intl library:**

```
$ cd ../..
$ npm run build
$ cd examples/translations/
```

Then you can build and run this example:

```
$ npm run build
$ npm start
```

or you can edit any source in `src/client` and recompile the example on the fly:

```
$ npm run watch
$ npm start
```
Your first run was in `/translations`, but readme says you have to `build`  inside project root first, and do not forget to `build` inside the `/translations'.
