### ISSUE TITLE
Intl + Jest + Formatting : "Cannot read property 'prototype' of undefined" 

### ISSUE THREAD

**Issue by doomy23** [yahoo/react-intl#93]
Hi guys!
I was working on some components that needed unit testing the other day and had to spend a long time to find a workaround for this bug I got while unit testing with Jest : 

```
TypeError: Cannot read property 'prototype' of undefined
        at null.<anonymous> (/home/droberge/git/eventshopper/node_modules/react-intl/node_modules/intl-format-cache/lib/memoizer.js:16:59)
        at exports.default._format (/home/droberge/git/eventshopper/node_modules/react-intl/lib/mixin.js:144:29)
        at exports.default.formatDate (/home/droberge/git/eventshopper/node_modules/react-intl/lib/mixin.js:66:21)
        at src$react$$.default.createClass.render (/home/droberge/git/eventshopper/node_modules/react-intl/lib/components/date.js:21:56)
        at ReactCompositeComponentMixin._renderValidatedComponent (/home/droberge/git/eventshopper/node_modules/react/lib/ReactCompositeComponent.js:1260:34)
        at wrapper [as _renderValidatedComponent] (/home/droberge/git/eventshopper/node_modules/react/lib/ReactPerf.js:50:21)
        at ReactCompositeComponentMixin.mountComponent (/home/droberge/git/eventshopper/node_modules/react/lib/ReactCompositeComponent.js:802:14)
        at wrapper [as mountComponent] (/home/droberge/git/eventshopper/node_modules/react/lib/ReactPerf.js:50:21)
        at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/droberge/git/eventshopper/node_modules/react/lib/ReactMultiChild.js:195:42)
        at ReactDOMComponent.Mixin._createContentMarkup (/home/droberge/git/eventshopper/node_modules/react/lib/ReactDOMComponent.js:260:32)
        at ReactDOMComponent.Mixin.mountComponent (/home/droberge/git/eventshopper/node_modules/react/lib/ReactDOMComponent.js:182:14)
        at ReactDOMComponent.wrapper [as mountComponent] (/home/droberge/git/eventshopper/node_modules/react/lib/ReactPerf.js:50:21)
        at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/droberge/git/eventshopper/node_modules/react/lib/ReactMultiChild.js:195:42)
        at ReactDOMComponent.Mixin._createContentMarkup (/home/droberge/git/eventshopper/node_modules/react/lib/ReactDOMComponent.js:260:32)
        at ReactDOMComponent.Mixin.mountComponent (/home/droberge/git/eventshopper/node_modules/react/lib/ReactDOMComponent.js:182:14)
        at ReactDOMComponent.wrapper [as mountComponent] (/home/droberge/git/eventshopper/node_modules/react/lib/ReactPerf.js:50:21)
        at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/home/droberge/git/eventshopper/node_modules/react/lib/ReactMultiChild.js:195:42)
        at ReactDOMComponent.Mixin._createContentMarkup (/home/droberge/git/eventshopper/node_modules/react/lib/ReactDOMComponent.js:260:32)
        at ReactDOMComponent.Mixin.mountComponent (/home/droberge/git/eventshopper/node_modules/react/lib/ReactDOMComponent.js:182:14)
        at ReactDOMComponent.wrapper [as mountComponent] (/home/droberge/git/eventshopper/node_modules/react/lib/ReactPerf.js:50:21)
        at ReactCompositeComponentMixin.mountComponent (/home/droberge/git/eventshopper/node_modules/react/lib/ReactCompositeComponent.js:808:44)
        at wrapper [as mountComponent] (/home/droberge/git/eventshopper/node_modules/react/lib/ReactPerf.js:50:21)
        at ReactCompositeComponentMixin.mountComponent (/home/droberge/git/eventshopper/node_modules/react/lib/ReactCompositeComponent.js:808:44)
        at wrapper [as mountComponent] (/home/droberge/git/eventshopper/node_modules/react/lib/ReactPerf.js:50:21)
        at ReactComponent.Mixin._mountComponentIntoNode (/home/droberge/git/eventshopper/node_modules/react/lib/ReactComponent.js:405:25)
        at ReactReconcileTransaction.Mixin.perform (/home/droberge/git/eventshopper/node_modules/react/lib/Transaction.js:134:20)
        at ReactComponent.Mixin.mountComponentIntoNode (/home/droberge/git/eventshopper/node_modules/react/lib/ReactComponent.js:381:19)
        at Object.ReactMount._renderNewRootComponent (/home/droberge/git/eventshopper/node_modules/react/lib/ReactMount.js:312:25)
        at Object.wrapper [as _renderNewRootComponent] (/home/droberge/git/eventshopper/node_modules/react/lib/ReactPerf.js:50:21)
        at Object.ReactMount.render (/home/droberge/git/eventshopper/node_modules/react/lib/ReactMount.js:381:32)
        at Object.wrapper [as render] (/home/droberge/git/eventshopper/node_modules/react/lib/ReactPerf.js:50:21)
        at Object.ReactTestUtils.renderIntoDocument (/home/droberge/git/eventshopper/node_modules/react/lib/ReactTestUtils.js:48:18)
        at Spec.<anonymous> (/home/droberge/git/eventshopper/eventshopper/js/picktickets/components/__tests__/EventSelector.test.jsx:82:35)
        at jasmine.Block.execute (/home/droberge/git/eventshopper/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:1065:17)
        at jasmine.Queue.next_ (/home/droberge/git/eventshopper/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2098:31)
        at null._onTimeout (/home/droberge/git/eventshopper/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2088:18)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

I found that the error occured in **mixin.js** : the Intl global variable is not defined in unit test so it fails at creating **getDateTimeFormat** : 

```javascript
    getNumberFormat  : intl$format$cache$$.default(Intl.NumberFormat),
    getDateTimeFormat: intl$format$cache$$.default(Intl.DateTimeFormat),
```
One way to solve it would be to import Intl into the mixin and tell Jest to unmock it, but as it required editing the module I tried to find a workaround and here's what I did : 

Instead of using dates components <ReactIntl.Date> I used {this.**formatDate**(...)} in the component that I test... and I need to do this with Jest : 

```javascript
jest.dontMock('intl');
jest.dontMock('react-intl');
jest.dontMock('intl-format-cache');

describe('EventSelector', function() {
  var Intl, ReactIntl, ReactIntlMixin;

  beforeEach(function(){
    Intl = require('intl');
    ReactIntl = require('react-intl');
    ReactIntlMixin = ReactIntl.Mixin;
    ReactIntlMixin.getDateTimeFormat = require("intl-format-cache").default(Intl.DateTimeFormat);
```

I basically redefine **getDateTimeFormat** before each test. 
It works but it's quite annoying. Do you have any better workaround for this issue...

Thank you!

**Comment by caridy** [comment]
@doomy23 `Intl.*` is a runtime requirement for react-intl, and it is your responsibility to guarantee that by loading a polyfill if your runtime does not support `Intl`. We can't require it in the mixin because Intl is not a module. More details here: http://formatjs.io/guide/#patch-runtime

**Comment by e741983** [comment]
sir can i ask what is needed to be set up to be able to define Jest? thanks
